import type { Place } from '../features/places/placeTypes';

// Mock data for MVP development
export const mockPlaces: Place[] = [
  {
    id: '1',
    name: 'Maiden Tower',
    description: 'Historic tower and UNESCO World Heritage Site in the Old City',
    address: 'Old City, Baku',
    latitude: 40.3661,
    longitude: 49.8372,
    rating: 4.5,
    tags: ['historical', 'museum', 'family-friendly'],
    priceRange: 'moderate',
  },
  {
    id: '2',
    name: 'Flame Towers',
    description: 'Modern skyscrapers symbolizing Azerbaijan\'s oil wealth',
    address: '1 Mehdi Huseyn Street, Baku',
    latitude: 40.3533,
    longitude: 49.8328,
    rating: 4.7,
    tags: ['entertainment', 'shopping', 'romantic'],
    priceRange: 'expensive',
  },
  {
    id: '3',
    name: 'Heydar Aliyev Center',
    description: 'Stunning architectural masterpiece by Zaha Hadid',
    address: '1 Heydar Aliyev Avenue, Baku',
    latitude: 40.3953,
    longitude: 49.8672,
    rating: 4.8,
    tags: ['museum', 'entertainment', 'family-friendly'],
    priceRange: 'moderate',
  },
  {
    id: '4',
    name: 'Baku Boulevard',
    description: 'Beautiful seaside promenade perfect for walking',
    address: 'Baku Boulevard, Baku',
    latitude: 40.3676,
    longitude: 49.8372,
    rating: 4.6,
    tags: ['park', 'family-friendly', 'romantic'],
    priceRange: 'budget',
  },
  {
    id: '5',
    name: 'Firuze Restaurant',
    description: 'Traditional Azerbaijani cuisine in elegant setting',
    address: '15 Nizami Street, Baku',
    latitude: 40.3756,
    longitude: 49.8328,
    rating: 4.4,
    tags: ['restaurant', 'romantic'],
    priceRange: 'expensive',
  },
];
